# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
          entity:
            class: AppBundle:Usuario
            property: correo
    encoders:
      AppBundle\Entity\Usuario:
        algorithm: bcrypt
    role_hierarchy:
      ROLE_ADMIN: [ROLE_DEPARTMENT, ROLE_USER]
      ROLE_DEPARTMENT: [ROLE_USER]


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            anonymous: ~
            pattern: ^/(login|reset)
        main:
            form_login:
              login_path: login
              check_path: login_check
            logout:
              path: logout
              target: homepage
    access_control:
        #Rutas para los admin
       # - { path: ^/admin, roles: ROLE_DEPARTMENT }
